name: 'Run Unit Tests and Generate Code Coverage'

description: 'Reusable action to run unit tests on a .NET project and generate a code coverage report.'

inputs:
  project:
    description: |
      The path to the .NET unit test project. 
      The path should be relative to the repository root.
    required: true
  exclude-files:
    description: |
      Files to exclude from code coverage analysis.
      Supports glob patterns.
    required: false
    default: ''
  exclude-modules:
    description: 'Modules to exclude from code coverage analysis'
    required: false
    default: ''
  threshold:
    description: 'Code coverage threshold percentage'
    required: false
    default: 0
  dotnet-version:
    description: 'The .NET SDK version to use'
    default: '6.0'
    options:
      - '8.0'
      - '7.0'
      - '6.0'

outputs:
  coverage-report-path:
    description: 'Path to the generated code coverage report directory'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    UNIT_TEST_PROJECT: ${{ inputs.project }} 
    UNIT_TEST_EXCLUDE_FILES: ${{ inputs.exclude-files }} 
    UNIT_TEST_EXCLUDE_MODULES: ${{ inputs.exclude-modules }} 
    UNIT_TEST_COVERAGE_THRESHOLD: ${{ inputs.threshold }} 
    DOTNET_VERSION: ${{ inputs.dotnet-version }}
  args:
    - ${{ inputs.project }}

